package org.davic.mpeg.sections;
 /**
  * This class is used to report a complete section being filtered. It is generated by 
  * SimpleSectionFilter, TableSectionFilter and RingSectionFilter objects when a section 
  * matching the filtering pattern is successfully filtered from the transport stream.
  */
public class SectionAvailableEvent
	extends org.davic.mpeg.sections.SectionFilterEvent
{
 /**
  * This constructs a SectionAvailable event for the specified SectionFilter object.
  * @param f the SectionFilter object which filtered the data.
  * @param appData application data that was passed to the startFiltering method
  */
  public SectionAvailableEvent( SectionFilter f, Object appData)
	{
	  super(f,appData);
	}
 /**
  * This returns the SectionFilter object which filtered the data.
  */
  	public Object getSource()
	{
	  return null;
	}
}

