package org.ocap.dvr;

import org.ocap.dvr.TimeShiftEvent;

/**
 * The TimeShiftListener interface is implemented by
 * applications wishing to receive events related to
 * time shift resources.
 */
public interface TimeShiftListener extends java.util.EventListener
{
   /**
    * Notifies the TimeShiftListener of an event generated by 
    * time-shift resource handling.
    *
    * @param e The generated event.
    */
   public void receiveTimeShiftevent(TimeShiftEvent e);

}
