

package com.googlecode.jinahya.test;


import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;


/**
 *
 * @author Jin Kwon <jinahya at gmail.com>
 */
@ApplicationPath("/rest")
public class BasicRestfulWebApplication extends Application {


    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }


    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.googlecode.jinahya.test.ImageFileSuffixesResource.class);
        resources.add(com.googlecode.jinahya.test.ImageFormatNamesResource.class);
        resources.add(com.googlecode.jinahya.test.ImageMediaTypesResource.class);
        resources.add(com.googlecode.jinahya.test.SchemaXsdResource.class);
        resources.add(com.googlecode.jinahya.test.SystemPropertiesResource.class);
    }
}
